/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppProfileIndexRouteImport } from './routes/_app/profile/index'
import { Route as AppCharactersIndexRouteImport } from './routes/_app/characters/index'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppRaidsHistoryIndexRouteImport } from './routes/_app/raids/history/index'
import { Route as AppRaidsCreateIndexRouteImport } from './routes/_app/raids/create/index'
import { Route as AppAdminUsersIndexRouteImport } from './routes/_app/admin/users/index'
import { Route as AppAdminSchoolsIndexRouteImport } from './routes/_app/admin/schools/index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCharactersIndexRoute = AppCharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRaidsHistoryIndexRoute = AppRaidsHistoryIndexRouteImport.update({
  id: '/raids/history/',
  path: '/raids/history/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRaidsCreateIndexRoute = AppRaidsCreateIndexRouteImport.update({
  id: '/raids/create/',
  path: '/raids/create/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminSchoolsIndexRoute = AppAdminSchoolsIndexRouteImport.update({
  id: '/admin/schools/',
  path: '/admin/schools/',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/characters/': typeof AppCharactersIndexRoute
  '/profile/': typeof AppProfileIndexRoute
  '/admin/schools/': typeof AppAdminSchoolsIndexRoute
  '/admin/users/': typeof AppAdminUsersIndexRoute
  '/raids/create/': typeof AppRaidsCreateIndexRoute
  '/raids/history/': typeof AppRaidsHistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/login': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/characters': typeof AppCharactersIndexRoute
  '/profile': typeof AppProfileIndexRoute
  '/admin/schools': typeof AppAdminSchoolsIndexRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
  '/raids/create': typeof AppRaidsCreateIndexRoute
  '/raids/history': typeof AppRaidsHistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/_app/characters/': typeof AppCharactersIndexRoute
  '/_app/profile/': typeof AppProfileIndexRoute
  '/_app/admin/schools/': typeof AppAdminSchoolsIndexRoute
  '/_app/admin/users/': typeof AppAdminUsersIndexRoute
  '/_app/raids/create/': typeof AppRaidsCreateIndexRoute
  '/_app/raids/history/': typeof AppRaidsHistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/characters/'
    | '/profile/'
    | '/admin/schools/'
    | '/admin/users/'
    | '/raids/create/'
    | '/raids/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/characters'
    | '/profile'
    | '/admin/schools'
    | '/admin/users'
    | '/raids/create'
    | '/raids/history'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/login/'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/_app/characters/'
    | '/_app/profile/'
    | '/_app/admin/schools/'
    | '/_app/admin/users/'
    | '/_app/raids/create/'
    | '/_app/raids/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/characters/': {
      id: '/_app/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof AppCharactersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/raids/history/': {
      id: '/_app/raids/history/'
      path: '/raids/history'
      fullPath: '/raids/history/'
      preLoaderRoute: typeof AppRaidsHistoryIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/raids/create/': {
      id: '/_app/raids/create/'
      path: '/raids/create'
      fullPath: '/raids/create/'
      preLoaderRoute: typeof AppRaidsCreateIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/users/': {
      id: '/_app/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/admin/schools/': {
      id: '/_app/admin/schools/'
      path: '/admin/schools'
      fullPath: '/admin/schools/'
      preLoaderRoute: typeof AppAdminSchoolsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCharactersIndexRoute: typeof AppCharactersIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppAdminSchoolsIndexRoute: typeof AppAdminSchoolsIndexRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
  AppRaidsCreateIndexRoute: typeof AppRaidsCreateIndexRoute
  AppRaidsHistoryIndexRoute: typeof AppRaidsHistoryIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCharactersIndexRoute: AppCharactersIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppAdminSchoolsIndexRoute: AppAdminSchoolsIndexRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
  AppRaidsCreateIndexRoute: AppRaidsCreateIndexRoute,
  AppRaidsHistoryIndexRoute: AppRaidsHistoryIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
